http:
  rest-template:
    configs:
      default:
        read-timeout: 3000
        connection-timeout: 1000
        max-connection-count: 30
        max-connection-per-route: 30

  naver:
    auth:
      root-uri: https://nid.naver.com
    api:
      root-uri: https://openapi.naver.com

---

spring:
  config:
    activate:
      on-profile: local

http:
  naver:
    auth:
      client-id: OrLmkctsCrhLTJW9OR5J
      client-secret: pBGxdpkbpb

  mail:
   root-uri: http://localhost:10083
   token: secret-token
   read-timeout: 5000

---

spring:
  config:
    activate:
      on-profile: dev

http:
  naver:
    auth:
      client-id: OrLmkctsCrhLTJW9OR5J
      client-secret: pBGxdpkbpb

  mail:
    root-uri: http://localhost:10083
    token: secret-token
    read-timeout: 5000
