spring:
  cloud:
    openfeign:
      httpclient:
        hc5:
          enabled: true
        max-connections: 50
        max-connections-per-route: 30
      client:
        default-config: default
        config:
          default:
            connect-timeout: 1000
            read-timeout: 3000

---

spring:
  config:
    activate:
      on-profile: local

  cloud:
    openfeign:
      client:
        config:
          default:
            logger-level: FULL
          mail-client:
            url: http://localhost:10083
            read-timeout: 10000
            default-request-headers:
              X-SYSTEM-KEY: ${DEV_MAIL_TOKEN}
          naver-api-client:
            url: https://openapi.naver.com
          naver-oauth-client:
            url: https://nid.naver.com
            default-query-parameters:
              client_id: ${DEV_NAVER_CLIENT_ID}
              client_secret: ${DEV_NAVER_CLIENT_SECRET}
              grant_type: authorization_code

---

spring:
  config:
    activate:
      on-profile: dev

  cloud:
    openfeign:
      client:
        config:
          mail-client:
            url: http://dev-closememo-mailsender.default.svc.cluster.local:10083
            read-timeout: 10000
            default-request-headers:
              X-SYSTEM-KEY: ${DEV_MAIL_TOKEN}
          naver-api-client:
            url: https://openapi.naver.com
          naver-oauth-client:
            url: https://nid.naver.com
            default-query-parameters:
              client_id: ${DEV_NAVER_CLIENT_ID}
              client_secret: ${DEV_NAVER_CLIENT_SECRET}
              grant_type: authorization_code

---

spring:
  config:
    activate:
      on-profile: real

  cloud:
    openfeign:
      client:
        config:
          mail-client:
            url: http://closememo-mailsender.default.svc.cluster.local:10083
            read-timeout: 10000
            default-request-headers:
              X-SYSTEM-KEY: ${MAIL_TOKEN}
          naver-api-client:
            url: https://openapi.naver.com
          naver-oauth-client:
            url: https://nid.naver.com
            default-query-parameters:
              client_id: ${NAVER_CLIENT_ID}
              client_secret: ${NAVER_CLIENT_SECRET}
              grant_type: authorization_code
